version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      working_dir: /application
      volumes:
        - ./code:/application
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - ./code:/application
          - ./phpdocker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    app:
      build: phpdocker/php-fpm
      working_dir: /application
      volumes:
        - ./code:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

